### PR TITLE
luci2-ui-base: fix l2.cgi.js validation messages

### PR DESCRIPTION
**Pull request by feckert**
Signed-off-by: Florian Eckert <Eckert.Florian@googlemail.com>

### CODE REVIEW

**Comment by jow-** [comment]
This commit looks wrong to me, what you're actually fixing here?

**Comment by feckert** [comment]
When the input will be validated then i want to see the range or min/max values what the input expects.

- Now i will see:

`Must be a number between %d and %d`

- After that i will see

`Must be a number between 0 and 4294967295`

**Comment by jow-** [comment]
Ok but then use the format function to interpolate values:
`gettext('Must be a number between %d and %d').format(min, max)`

**Comment by jow-** [comment]
Merged manually with two tiny white space changes, thanks!

**Pull request closed without merging**
