### PR TITLE
Add backup page

### PR DESCRIPTION
**Pull request by feckert**
Add Backup page to luci2.

### CODE REVIEW

**Comment by jow-** [comment]
Great work @feckert, I've just a few remarks:
- Can you make the default strings english instead of german?
- Maybe it makes sense to fold the l2cgi service into the l2rpc one? Even if not it might make sense to grab the token from there to avoid the duplicate calls.
- Maybe we should add some error handling in case FormData support is not available? We could display a modal backup then.

**Comment by feckert** [comment]
Hello Jow,

1. yes i can do this. In the future is there a plan to make it multi language? If yes what is your preferred implementation. Maybe I can do it multi language for this module first.

2. Good remark i have already notice this and it is not very smart how i did this. Maybe it is better to make a token factory to get/set token from every submodule who need it?

3. Why? is FormData not available on every Browser?

**Comment by jow-** [comment]
Yes, I plan to support localization. Note that we already use angular gettext so in order to start translating strings you'd need to follow https://angular-gettext.rocketeer.be/dev-guide/getting-started/

I didn't invest any time in translation yet though as it is a mostly moving target at this point in time.

**Comment by feckert** [comment]
Hello Jow,

i have edit your remarks.
But I m not sure what you mean in your third remarks "FormData".
Could you please explain.

Kind Regards

Flo

**Comment by jow-** [comment]
Forget about my FormData comment, I've checked and all recent browsers are implementing it properly. Thanks for your PR!

**Pull request merged**
