### PR TITLE
luci2-app-dsl: add lantiq dsl status view

### PR DESCRIPTION
**Pull request by feckert**
This app adds a dsl status overview for lantiq xrx200 devices 
Signed-off-by: Florian Eckert <Eckert.Florian@googlemail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Merged, thanks!

**Comment by jow-** [comment]
Just a tip: sending SIGHUP to rpcd is enough to make it pick up new plugins, no need for a full restart.

**Comment by feckert** [comment]
Thanks for merging. Should I update the Makefile?

**Comment by jow-** [comment]
You could do a followup PR if you like

**Pull request merged**
